service: worthawatch-import
app: worthawatch-import
tenant: ianfeather
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameterHistory"
        - "ssm:GetParametersByPath"
        - "ssm:GetParameters"
        - "ssm:GetParameter"
      Resource: "arn:aws:ssm:us-east-1:453352932084:parameter/*"

functions:
  import:
    handler: handler.import

package:
  exclude:
    - test/**
