service: worthawatch-import
app: worthawatch-import
tenant: ianfeather
provider:
  name: aws
  runtime: nodejs8.10
  profile: worthawatch

functions:
  import:
    handler: handler.import

package:
  exclude:
    - test/**
